name: indones_ai
description: "An Indonesian AI assistant mobile app using Flutter."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  provider: ^6.1.1
  # HTTP Client
  http: ^1.1.2
  # Text to Speech
  flutter_tts: ^3.8.5
  # UI Components
  flutter_markdown: ^0.6.18
  shimmer: ^3.0.0
  # Firebase
  firebase_core: 3.6.0
  firebase_auth: 5.3.1
  cloud_firestore: 5.4.4
  cloud_functions: 5.1.3
  # Internationalization
  intl: ^0.18.1
  firebase_auth_web: 5.13.2
  # File and Image Picking
  file_picker: ^6.1.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
