name: indonesai
description: An AI-powered assistant application for Indonesian users.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  firebase_auth_web: ^5.13.3
  cloud_firestore: ^5.4.5
  cloud_functions: ^5.1.4
  flutter_tts: ^4.0.0
  http: ^1.1.0
  file_picker: ^6.2.1
  image_picker: ^1.0.0
  cupertino_icons: ^1.0.2
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
